package com.jeff.yuan.cms.entity;
// Generated 2018-11-6 15:20:46 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ShopTradeDetail generated by hbm2java
 */
@Entity
@Table(name = "shop_trade_detail", catalog = "yuan")
public class ShopTradeDetail implements java.io.Serializable {

	private Integer id;
	private int tradeId;
	private int proId;
	private byte count;
	private int price;
	private String proName;
	private String proLogoImg;

	public ShopTradeDetail() {
	}

	public ShopTradeDetail(int tradeId, int proId, byte count, int price, String proName, String proLogoImg) {
		this.tradeId = tradeId;
		this.proId = proId;
		this.count = count;
		this.price = price;
		this.proName = proName;
		this.proLogoImg = proLogoImg;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "trade_id", nullable = false)
	public int getTradeId() {
		return this.tradeId;
	}

	public void setTradeId(int tradeId) {
		this.tradeId = tradeId;
	}

	@Column(name = "pro_id", nullable = false)
	public int getProId() {
		return this.proId;
	}

	public void setProId(int proId) {
		this.proId = proId;
	}

	@Column(name = "count", nullable = false)
	public byte getCount() {
		return this.count;
	}

	public void setCount(byte count) {
		this.count = count;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Column(name = "pro_name", nullable = false, length = 64)
	public String getProName() {
		return this.proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	@Column(name = "pro_logo_img", nullable = false, length = 64)
	public String getProLogoImg() {
		return this.proLogoImg;
	}

	public void setProLogoImg(String proLogoImg) {
		this.proLogoImg = proLogoImg;
	}

}
